name: PCK.AUTOMIC_SMB
source: ae
binaries:
- object: RESOURCES/LIBS/PCK.AUTOMIC_SMB.PRV.STORE
  resources:
  - name: SMBTOOL.JAR
    type: BINARY
    path: tools/smb-tool/target/smb-tool.jar
    version: 1.2.2
  - name: JCIFS.JAR
    type: BINARY
    path: tools/jcifs/jcifs.jar
    version: 1.3.17
  - name: JCIFS.SOURCE.JAR
    type: BINARY
    path: tools/jcifs/jcifs-1.3.17-sources.jar
    version: 1.3.17
- object: RESOURCES/PCK.AUTOMIC_SMB.PRV.CUSTOM_TYPES
  timestamp: disabled
  resources:
  - name: ARTIFACTSOURCE#SMB
    type: TEXT
    path: ara/types/artifact/Artifact_SMB_1.0.0.xml
    version: 1.0.0
